replicaCount: 1

image:
  repository: mayurkumar0393/dotnet-sample
  pullPolicy: IfNotPresent
  tag: "0.1.0"

podAnnotations:
  cert-manager.io/issuer: letsencrypt-prod

service:
  type: ClusterIP
  port: 80

ingress:
  enabled: true
  annotations:
    cert-manager.io/issuer: letsencrypt-prod
    kubernetes.io/ingress.class: nginx
  
  hosts:
    - host: dotnet-sample.mkumar.me
      paths:
      - /
  tls:
   - secretName: dotnet-prod-tls
     hosts:
       - dotnet-sample.mkumar.me

resources:
  limits:
    cpu: 100m
    memory: 128Mi
  requests:
    cpu: 100m
    memory: 128Mi

autoscaling:
  enabled: false
  minReplicas: 2
  maxReplicas: 5
  targetCPUUtilizationPercentage: 80
  targetMemoryUtilizationPercentage: 80
