name: Build Pull Request

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 3.1.101
    - name: Install dependencies
      run: dotnet restore
      working-directory: "WebApplication1"
    - name: Build
      run: dotnet build "WebApplication1.csproj" -c Release -o ./build --no-restore
      working-directory: "WebApplication1"
    - name: Test
      run: dotnet test --no-restore --verbosity normal
      working-directory: "WebApplication1"
  
  docker:
    name: build docker image
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Docker build
        run:  docker build -f "./WebApplication1/Dockerfile" --label "created-by=GitHub-Pull-Reqeust" --label "project-name=WebApplication1" .
        continue-on-error: false
